- src/config/lexer.rs
- src/config/mod.rs
- src/config/parser.rs
Adds a new helper function in `config`, `config::get_entries`, that takes in a peekable character iterator and returns an iterator over `Entry`s. Also fixes mutability / borrowing issues in both `Lexer` and `Parser` to make this possible.
> refactor: add helper function to get entries

- src/config/mod.rs
- src/config/parser.rs
This is to replace "implicit information types" such as `(option<lexer::Token>, ParseError)` with just a simple `ParseError`.
> refactor(config): change ParseError to encapsulate both token and ParseErrorType

- src/bin/ambit/directories.rs
- src/bin/ambit/main.rs
- src/config/mod.rs
- src/error.rs
The `check` command can be used to "Check ambit configuration for errors". In other words, it retrieves config entries and outputs if there are any syntax errors present.
In addition to the check command, this PR introduces the `sync` command; however, this is unimplemented.
In terms of errors, this change makes `AmbitError` and `ParseError` implement `std::error::Error`.
> feat: implement check command

- src/bin/ambit/main.rs
This PR simply renames the `create_paths()` function to `ensure_paths_exist()`. It also removes unnecessary `match` statements.
> refactor: rename path creation function

- src/bin/ambit/main.rs
- src/config/ast.rs
- src/config/mod.rs
- src/config/parser.rs
This changes the file structure to split up the responsibilities of each file (config/parser.rs is for parsing, config/ast.rs is for defining the AST types). It also adds a test and fixes a bug involving it.
> refactor(config): change file structure, add tests

- src/bin/ambit/directories.rs
- src/error.rs
Renames the configuration file from `config` to `config.ambit`. This will make it easier to recognize the ambit file type (which may make syntax highlighting implementation easier in the future).
This PR also improves the error on `File::open()` function call by explicitly informing the user of the expected configuration location and the error received:
```
ERROR: Failed to read `/home/user/.config/ambit/config.ambit`
Caused by:
No such file or directory (os error 2)
```
Previous behavior only printed out the reason for failure (`No such file or directory (os error 2)`) which may be vague for the end user.
> refactor: rename config and improve error message

- src/config/ast.rs
- src/config/mod.rs
- src/config/parser.rs
- src/config/strgen.rs
This adds the ability to iterate over possible strings in a Spec by using the `IntoIterator` trait. An example of usage may be:
```rust
let spec = spec_divined_from_somewhere();
for path in spec.into_iter() {
do_something_with(path);
}
```
> feat: add ability to iterate over possible strings in a Spec

- README.md
The README.md stated the configuration file name as `config` rather than `config.ambit` as changed in PR #26. 
This PR fixes this.
> docs: update config name in readme

- .github/workflows/rust.yml
Adds testing for Windows. (This may be useful later on for when we do platform-specific stuff.)
> ci: add Windows Server 2019 testing

- src/bin/ambit/cmd.rs
- src/bin/ambit/directories.rs
- src/bin/ambit/main.rs
- src/error.rs
This PR implements the `sync` command.
```
Sync files in dotfile repository to system through symbolic links
USAGE:
ambit sync [FLAGS]
FLAGS:
--dry-run    If set, do not actually symlink the files
-h, --help       Prints help information
-q, --quiet      Don't report individual symlinks
```
To aid this, the PR also introduces a new `AmbitError` variant called `Symlink`.
Additionally, the `cmd` module previously defined in `src/bin/ambit/main.rs` is moved to its own module file in `src/bin/ambit/cmd.rs`.
> feat: implement sync command

- src/config/ast.rs
- src/config/parser.rs
- src/config/strgen.rs
This PR fixes #12.
It also refactors `Expr` to make test-making easier with `impl From<ExprType> for Expr`.
> feat: allow match expressions with no default

- src/bin/ambit/cmd.rs
- src/bin/ambit/directories.rs
- src/error.rs
This PR takes advantage of [`std::path::PathBuf::display`](https://doc.rust-lang.org/std/path/struct.PathBuf.html#method.display) method when attempting to print paths instead of `AmbitPath::as_str`. This avoids encountering a potential error if a path contains `non-UTF-8` string. The function calls have been changed in two places: `link` closure and `AmbitError`.
Additionally, a unit test is added to ensure that `Symlink` error formatting works.
> refactor: use path display where appropriate

- Cargo.toml
- src/bin/ambit/directories.rs
- tests/integration_tests.rs
This PR provides CLI-based integration tests.  To enable this, the PR introduces a way to change 3 paths through environment variables: (1) `AMBIT_HOME_PATH`, (2) `AMBIT_CONFIG_PATH`, and (3) `AMBIT_REPO_PATH`.
The integration tests are located in `tests/integration_tests.rs`. This file contains a struct named `AmbitTester` which implements a builder pattern to allow different filesystem/configuration environments to be simulated. This is done to ensure that the tests have no side-effects and are isolated from each other.
This testing framework should mean that future integration tests can be uniformly implemented.
To accomplish this, two `dev-dependencies` were added (`Cargo.toml`):
* assert_cmd
* tempfile
> test: add integration test

- src/config/ast.rs
- src/config/parser.rs
> feat(config): add ability to have trailing commas

- src/bin/ambit/cmd.rs
- tests/integration_tests.rs
Prior to this PR, `ambit sync` would return an error if the parent directories of the host file didn't exist. This PR fixes this by recursively creating the host file's parent directories in the `sync` function.
An additional integration test pertaining to this fix is added to ensure this functionality is permitted in future iterations.
> fix: make sync create host file parent directories

- tests/integration_tests.rs
This PR simply removes a superfluous `println!` call in the integration test.
> test: remove println in integration test

- src/config/ast.rs
- src/config/parser.rs
- src/config/strgen.rs
This PR implements `Expr::NotOs` and `Expr::NotHost`. In the configuration, these are invoked by `!os` and `!host` respectively. These expressions are evaluated as true if the os/hostname given is not present.
The `incorrect_os()` function was slightly refactored to return an incorrect os as a `String` to generalize its use across multiple unit test functions.
Unit tests have been added to ensure correct functionality of `Expr::NotOs` and `Expr::NotHost` expressions.
> feat(config): implement not os and not host

- src/bin/ambit/cmd.rs
- src/bin/ambit/main.rs
- src/error.rs
- tests/integration_tests.rs
The `-m` flag on the `sync` command moves config files into the repo if they already exist in their original location.
> feat: add -m flag to sync

- src/bin/ambit/cmd.rs
- src/bin/ambit/directories.rs
- tests/integration_tests.rs
This PR aims to make getting started with ambit easier. Before this PR, by default, if the `~/.config/ambit` directory didn't exist when `ambit init` or `ambit clone` is invoked, an error will occur:
```
ERROR: No such file or directory (os error 2)
```
This PR aims to fix this by ensuring that the parent directory of any file that is created through `AmbitPath` exists.
An additional integration test was added called `init_ambit_config_dir_does_not_exist` to ensure that this behavior works.
NOTE: The second commit in this PR, 39630d2, introduces better integration of the `ensure_parent_dirs_exist` function. This makes the solution of the initial problem to simply create the configuration file's parent directories before the file itself is created.
> fix: create configuration directory on initialize

- src/bin/ambit/cmd.rs
- src/bin/ambit/main.rs
- tests/integration_tests.rs
This PR implements the `clean` command invoked with `$ ambit clean`. This command has description `Remove all symlinks and delete host files`. Essentially, it reads the configuration, iterates through the entries, and deletes its host file (effectively removing the symlink). A host file will only be deleted if it is appropriate symlinked to the repo file.
Implementation-wise, the entry iteration logic has been vastly simplified for both `sync` and `clean` functions in `cmd.rs`.
An integration has been added to test `clean` functionality.
> feat: implement clean command

- Cargo.toml
- src/bin/ambit/cmd.rs
- src/bin/ambit/directories.rs
- src/bin/ambit/main.rs
- src/error.rs
- tests/integration_tests.rs
Implementation details:
* `walkdir` dependency added (`2.3.1`).
* New `AmbitError` variant `AmbitError::WalkDir`.
* Configuration file name has been defined as a global const variable.
* Integration test infrastructure has been refactored slightly to support the new tests and reduce repeated code:
* `with_config` and `with_repo_file` ensures the creation of the config and repo file respectively.
* `with_default_paths` has been refactored to `with_repo_path`, exact same functionality but doesn't create config file in the process.
* `write_stdin` function introduced.
> feat: implement use-repo-config sync option

- Cargo.toml
This PR adds some additional package information to `Cargo.toml` for easier integration with the AUR.
> docs: add additional package information

- src/bin/ambit/cmd.rs
- tests/integration_tests.rs
This PR fixes `clippy` warnings about using `&PathBuf` over `&Path`.
> fix: take path rather than pathbuf as argument

- Cargo.toml
- src/bin/ambit/cmd.rs
- src/config/ast.rs
- src/config/lexer.rs
- src/config/parser.rs
- src/config/strgen.rs
- src/error.rs
This PR implements pattern matching: a feature that permits the use of `*` and `?` to match against files and directories.
This feature requires the `patmatch 0.1.2` crate to facilitate the pattern matching process.
**Implementation details:**
The lexer has been slightly modified to avoid escaping `*` and `?`. The resulting string would then be handled in `cmd.rs` where it is passed to `Pattern::compile` from `patmatch`.
To find matching files and directories, an entry as part of the spec is split into components. For each component, a pattern is compiled and a vector of paths that match this pattern is found. With the vector produced from the previous component, the process is repeated with the ancestor paths equal to the said vector.
Unit tests have been added to test the following:
- …
> feat: implement pattern matching

- src/bin/ambit/cmd.rs
When invoking `ambit git`, this replaces the `ambit` process with the `git` process on Unix systems. This is non-trivial to do on Windows, and hence is only for Unix for now.
This enables stuff like git's automatic output coloring to work.
> fix(ambit git): replace ambit process with git on Unix systems
